file1<-read_excel("Centroid_Location1.xls")
install.packages("readxl")
#access library
library("readxl")

sheet1 <- read_excel("Centroid_Location1.xlsx", sheet = 1)
sheet2 <- read_excel("Centroid_Location1.xlsx", sheet = 2)
sheet3 <- read_excel("Centroid_Location1.xlsx", sheet = 3)
sheet4 <- read_excel("Centroid_Location1.xlsx", sheet = 4)
sheet5 <- read_excel("Centroid_Location1.xlsx", sheet = 5)
sheet6 <- read_excel("Centroid_Location1.xlsx", sheet = 6)
sheet7 <- read_excel("Centroid_Location1.xlsx", sheet = 7)
sheet8 <- read_excel("Centroid_Location1.xlsx", sheet = 8)

sheet9 <- read_excel("Centroid_Location1.xlsx", sheet = 9)
sheet10 <- read_excel("Centroid_Location1.xlsx", sheet = 10)
sheet11 <- read_excel("Centroid_Location1.xlsx", sheet = 11)
sheet12 <- read_excel("Centroid_Location1.xlsx", sheet = 12)
sheet13 <- read_excel("Centroid_Location1.xlsx", sheet = 13)
sheet14 <- read_excel("Centroid_Location1.xlsx", sheet = 14)
sheet15 <- read_excel("Centroid_Location1.xlsx", sheet = 15)
sheet16 <- read_excel("Centroid_Location1.xlsx", sheet = 16)
sheet17 <- read_excel("Centroid_Location1.xlsx", sheet = 17)
sheet18 <- read_excel("Centroid_Location1.xlsx", sheet = 18)
sheet19 <- read_excel("Centroid_Location1.xlsx", sheet = 19)
sheet20 <- read_excel("Centroid_Location1.xlsx", sheet = 20)
sheet21 <- read_excel("Centroid_Location1.xlsx", sheet = 21)
sheet22 <- read_excel("Centroid_Location1.xlsx", sheet = 22)
sheet23 <- read_excel("Centroid_Location1.xlsx", sheet = 23)
sheet24 <- read_excel("Centroid_Location1.xlsx", sheet = 24)
sheet25 <- read_excel("Centroid_Location1.xlsx", sheet = 25)
sheet26 <- read_excel("Centroid_Location1.xlsx", sheet = 26)
sheet27 <- read_excel("Centroid_Location1.xlsx", sheet = 27)
sheet28 <- read_excel("Centroid_Location1.xlsx", sheet = 28)
sheet29 <- read_excel("Centroid_Location1.xlsx", sheet = 29)
sheet30 <- read_excel("Centroid_Location1.xlsx", sheet = 30)
sheet31 <- read_excel("Centroid_Location1.xlsx", sheet = 31)
sheet32 <- read_excel("Centroid_Location1.xlsx", sheet = 32)
sheet33 <- read_excel("Centroid_Location1.xlsx", sheet = 33)
sheet34 <- read_excel("Centroid_Location1.xlsx", sheet = 34)
sheet35 <- read_excel("Centroid_Location1.xlsx", sheet = 35)
sheet36 <- read_excel("Centroid_Location1.xlsx", sheet = 36)
sheet37 <- read_excel("Centroid_Location1.xlsx", sheet = 37)
sheet38 <- read_excel("Centroid_Location1.xlsx", sheet = 38)
sheet39 <- read_excel("Centroid_Location1.xlsx", sheet = 39)
sheet40 <- read_excel("Centroid_Location1.xlsx", sheet = 40)
sheet41 <- read_excel("Centroid_Location1.xlsx", sheet = 41)
sheet42 <- read_excel("Centroid_Location1.xlsx", sheet = 42)
sheet43 <- read_excel("Centroid_Location1.xlsx", sheet = 43)
sheet44 <- read_excel("Centroid_Location1.xlsx", sheet = 44)
sheet45 <- read_excel("Centroid_Location1.xlsx", sheet = 45)
sheet46 <- read_excel("Centroid_Location1.xlsx", sheet = 46)
sheet47 <- read_excel("Centroid_Location1.xlsx", sheet = 47)
sheet48 <- read_excel("Centroid_Location1.xlsx", sheet = 48)
sheet49 <- read_excel("Centroid_Location1.xlsx", sheet = 49)
sheet50 <- read_excel("Centroid_Location1.xlsx", sheet = 50)

